webapp/__init__.py
import os
import logging

from werkzeug.contrib.cache import SimpleCache
from flask import Flask

# local import
from config import app_config


def get_config():
    try:
        config = os.getenv('APP_CONFIG', u'devel')
        return config
    except Exception as e:
        print(e.message)
        os.abort()

# setup the cache. I had to use this kind of cache due to the time limit
cache = SimpleCache()

# get the current configuration from environment variable APP_CONFIG
config = get_config()

app = Flask(__name__, instance_relative_config=True)

# load the config.py file
logging.debug(u'Starting with {} configuration'.format(config))
app.config.from_object(app_config[config])

# Set the logging level if settled in config file otherwise set to WARNING level
logging.basicConfig()
level = app.config.get('LOGGING_LEVEL', logging.WARNING)
logging.getLogger().setLevel(level)

# import all the routes
from routes import startup, index
from webapp.api.v1.routes import mod_api_v1 as api_v1

# register the blueprints
app.register_blueprint(api_v1, url_prefix='/api/v1')

webapp/api/v1/routes.py
from flask import Blueprint, jsonify, request
from webapp.api.v1.Currency import Currency
from webapp.api.v1.Pricing import Pricing

mod_api_v1 = Blueprint('api_v1', __name__, url_prefix='/api/v1')


@mod_api_v1.route('/products', methods=['GET'])
def products():
    """Get the full list of products
    """
    try:
        prods = Pricing.get_products()
        return jsonify(prods), 200
    except Exception as e:
        return jsonify(e.message), 500


@mod_api_v1.route('/product/<int:product_id>', methods=['GET'])
def product(product_id):
    """Get the details of the product given id

       Args:
           product_id: The id of the product

       Return:
           All the info of the products
    """

    try:
        prods = Pricing.get_products()
        prod = prods[product_id]
        return jsonify(prod), 200
    except KeyError:
        return jsonify(u'product_id not found: {}'.format(product_id)), 500
    except Exception as e:
        return jsonify(e.message), 500


@mod_api_v1.route('/vat_bands', methods=['GET'])
def vat_bands():
    """Get the full list of vat bands
    """
    try:
        vats = Pricing.get_vat_bands()
        return jsonify(vats), 200
    except Exception as e:
        return jsonify(e.message), 500


@mod_api_v1.route('/vat_band/<vat_band_id>', methods=['GET'])
def vat_band(vat_band_id):
    """Get vat band of given id
       Args:
           vat_band_id: The id of the vat band

       Return:
           The value of the given vat band
    """

    try:
        vats = Pricing.get_vat_bands()
        vat = vats[vat_band_id]
        return jsonify(vat), 200
    except KeyError:
        return jsonify(u'vat_band_id not found: {}'.format(vat_band_id)), 500
    except Exception as e:
        return jsonify(e.message), 500


@mod_api_v1.route('/currencies', methods=['GET'])
def currencies():
    """Get the full list of valid currencies
    """
    try:
        currs = Currency.get_currencies()
        return jsonify(currs), 200
    except Exception as e:
        return jsonify(e.message), 500


@mod_api_v1.route('/currency_rate/<currency>', methods=['GET'])
def currency_rate(currency):
    """Get the exchange rate for GBP to given currency
    """
    try:
        rate = Currency.get_exchange_rate(currency)
        return jsonify(rate), 200
    except Exception as e:
        return jsonify(e.message), 500


@mod_api_v1.route('/pricing_info', methods=['POST'])
def pricing_info():

    if not request.is_json:
        return jsonify(u'Invalid request format - only json accepted'), 400

    try:
        order = Pricing.get_totals(request.json)
        return jsonify(order), 200
    except Exception as e:
        return jsonify(e.message[u'text']), e.message[u'code']

webapp/templates/index.html
{% extends "template.html" %}

{% block searchbar %}
{% endblock %}

{% block style_block %}
{% endblock %}

{% block notification %}
{% endblock %}

{% block content %}
<section class="section-content" ng-controller="tailsApp" ng-cloak>
    <div class="currencies">
        <h6 for="ddCurrecies">_{currencies[currency]['currencyName']}_ (GBP_{currency}_: _{rate}_)</h6>
        <a class='dropdown-button btn' href='#' data-activates='ddCurrecies'>_{currency}_</a>
        <ul id='ddCurrecies' class='dropdown-content'>
            <li ng-repeat="c in currencies|toArray|orderBy:'id'">
                <a href="#!" ng-click="currency_click(this)" data-value="_{c['id']}_">_{c['id']}_ - _{c['currencyName']}_</a>
            </li>
        </ul>
    </div>
	<div class="progress" ng-show="loading">
		<div class="indeterminate"></div>
	</div>
    <div class="left">
        <h5>Products</h5><br />
        <ul class="collection" >
          <li class="collection-item" ng-repeat="(k,v) in products">
              <div class="productName">Products _{k}_</div>
              <span>_{applyExchange(v['price'])}_</span> _{currency}_ + _{vat_bands[v['vat_band']]*100}_% VAT
              <a class="btn-floating btn-small waves-effect waves-light add" ng-click="addProduct(k)"><i class="material-icons">add</i></a>
              <a class="btn-floating btn-small waves-effect waves-light remove" ng-click="removeProduct(k)"><i class="material-icons">remove</i></a>
          </li>
        </ul>
    </div>
    <div class="right">
        <h5>Basket</h5><br />
        <ul class="collection" ng-if="(basket|toArray).length > 0">
          <li class="collection-item" ng-repeat="(k,v) in basket">
              <div class="productName">Products _{k}_</div>
              <span>_{applyExchange(products[k]['price'])}_</span> _{currency}_ + _{vat_bands[products[k]['vat_band']]*100}_% VAT
              <div class="qty">_{v}_</div>
          </li>
          <li class="collection-item">
              <div class="productName">Total</div>
              <span>_{total['order_total_price']}_</span> _{currency}_
              + _{total['order_total_vat']}_ of VAT
              = _{round(total['order_total_price']+total['order_total_vat'], 2)}_ _{currency}_
          </li>
        </ul>
    </div>
</section>
{% endblock %}

{% block tail_script%}
<script>
app.controller('tailsApp', function($scope, $http, $timeout) {
    // Set the default values at startup
    $scope.currency = "GBP";
    $scope.rate = 1;
    $scope.basket = {};
    $scope.loading = true;
	
    /* Get the list of products */
    var url = "{{url_for('api_v1.products')}}";
    $http.get(url).then(function(data) {
        $scope.products = data.data;
    });

    / *Get the list of vat_band */
    var url = "{{url_for('api_v1.vat_bands')}}";
    $http.get(url).then(function(data) {
        $scope.vat_bands = data.data;
    });

    /* Get the list of currencies and init the dropdown */
    var url = "{{url_for('api_v1.currencies')}}";
    $http.get(url).then(function(data) {
        $scope.currencies = data.data;

        $timeout(function() {
            $('.dropdown-button').dropdown({
                inDuration: 300,
                outDuration: 225,
                constrainWidth: false, // Does not change width of dropdown to that of the activator
                hover: true, // Activate on hover
                gutter: 0, // Spacing from edge
                belowOrigin: false, // Displays dropdown below the button
                alignment: 'left', // Displays dropdown with edge aligned to the left of button
                stopPropagation: false // Stops event propagation
            });
			
			$scope.loading = false;
        }, 0);
    });

    /* change the current currency */
    $scope.currency_click = function(e) {
		$scope.loading = true;
        $scope.currency = e.c.id;
        if ($scope.currency == "GBP") {
            $scope.rate = 1;
			$scope.loading = false;
        }
        else {
            var url = "{{url_for('api_v1.currency_rate', currency=':currency')}}".replace(":currency", $scope.currency);
            $http.get(url).then(function(data) {
                $scope.rate = data.data;
				$scope.loading = false;
            });
        }
    }

    /* calculate the price in the given currency */
    $scope.applyExchange = function(price) {
        return $scope.round(price * $scope.rate, 2);
    }

    /* round the price to the given decimal */
    $scope.round = function(value, decimals) {
        return Number((Math.round(value + "e" + decimals)  + "e-" + decimals));
    }

    /* add a product to the basket */
    $scope.addProduct = function(prod_id) {
        if (!(prod_id in $scope.basket))
            $scope.basket[prod_id] = 1;
        else
            $scope.basket[prod_id] += 1;

        //console.log('$scope.basket[' + prod_id + '] = ' + $scope.basket[prod_id]);
        $scope.basket_total();
    }

    /* remove a product to the basket */
    $scope.removeProduct = function(prod_id) {
        if (!(prod_id in $scope.basket))
            return;

        if ($scope.basket[prod_id] > 1) {
            $scope.basket[prod_id] -= 1;
            //console.log('$scope.basket[' + prod_id + '] = ' + $scope.basket[prod_id]);
        }
        else {
            delete $scope.basket[prod_id];
            //console.log('$scope.basket[' + prod_id + '] = removed');
        }

        $scope.basket_total();
    }

    $scope.basket_total = function() {
        var items = Object.keys($scope.basket).map(function(order_id) {
            return {
                "product_id": parseInt(order_id),
                "quantity": $scope.basket[order_id],
            }
        });

        var data = {
            "order": {
                "id": 12345,
                "customer": {
                    "customer_id": 1,
                    "name": "Ignazio",
                    "surname": "Ingenito",
                },
                "items": items,
                "currency": $scope.currency,
            }
        }

        var url = "{{url_for('api_v1.pricing_info')}}";
        $http.post(url, data).then(
            function(data) {
                $scope.total = data.data;
                console.log(data.data);
            },
            function(data) {
                Materialize.toast(data.data, 3000);
            }
        );
    }
});

app.filter('toArray', function () {
    return function (obj, addKey) {
        if (obj==null)
            return;

        if ( addKey === false ) {
            return Object.keys(obj).map(function(key) {
                return obj[key];
            });
        } else {
            return Object.keys(obj).map(function (key) {
                if(typeof obj[key] == 'object') return Object.defineProperty(obj[key], '$key', {enumerable: false, value: key});
            });
        }
    }
});
</script>
{% endblock %}

webapp/templates/template.html
<!DOCTYPE html>
<html lang="{{html_lang}}" ng-app="tails">
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <!-- meta info -->
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="keywords" content="tails.com">
    <meta name="description" content="tails.com - pricing test">
    <meta name="author" content="Ignazio Ingenito">
    <meta name="template" content="{{ self._TemplateReference__context.name }}"/>
    <meta name="robots" content="noindex">
    <!-- Title -->
    <title>tails.com - pricing test</title>
    <!-- Versions -->
    {% set angular_ver = '1.6.7' %}
    {% set jquery_ver = '3.2.1' %}
    {% set materialize_ver = '0.100.2' %}
    {% set moment_ver = '2.22.1' %}
    <!-- common css  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css"/>
    <link href="//cdnjs.cloudflare.com/ajax/libs/materialize/{{materialize_ver}}/css/materialize.css" type="text/css"
          rel="stylesheet" media="screen,projection"/>
    <link href="//fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="//fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="/static/css/style.css" type="text/css" rel="stylesheet"/>

    <!-- specific page css  -->
    {% block style_block %}{# page-specific CSS #}{% endblock %}

    <!-- specific defer-incapable js block  -->
    {% block head_script %}{# defer-incapable JS block #}{% endblock %}
</head>
<body>
<!-- standard defer-capable js -->
<script src="//code.jquery.com/jquery-{{jquery_ver}}.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/{{moment_ver}}/moment.min.js"></script>
<!-- Language i18n {{locale}} -->
<!-- global defer-capable js -->
<script src="//ajax.googleapis.com/ajax/libs/angularjs/{{angular_ver}}/angular.min.js" crossorigin="anonymous"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/{{angular_ver}}/angular-resource.min.js"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular-i18n/1.5.0/angular-locale_{{session['user_locale']}}.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/{{angular_ver}}/angular-sanitize.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/{{materialize_ver}}/js/materialize.min.js"></script>

<script>
    var app = angular.module('tails', ['ngResource'])
                     .config(['$interpolateProvider', function ($interpolateProvider) {
                               $interpolateProvider.startSymbol('_{');
                               $interpolateProvider.endSymbol('}_'); }
                             ]);
</script>
<nav>
    <div class="nav-wrapper">
        <a href="https://tails.com"><img class="logo" src="static/img/logo-tm.svg" /></a>
        <a href="#" class="login">Log In</a>
        <h3 class="title">Pricing Test</h3>
    </div>
</nav>
<!-- content  -->
{% block content %}{# content block #}{% endblock %}
<!-- footer -->
{% block footer %}{# content-footer block #}{% endblock %}
<!-- specic page defer-capable custom js -->
{% block tail_script %}{# defer-capable JS block #}{% endblock %}
</body>
</html>